export default {
    "login": "davudahmedoff",
    "id": 121305285,
    "node_id": "U_kgDOBzr4xQ",
    "avatar_url": "https://avatars.githubusercontent.com/u/121305285?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/davudahmedoff",
    "html_url": "https://github.com/davudahmedoff",
    "followers_url": "https://api.github.com/users/davudahmedoff/followers",
    "following_url": "https://api.github.com/users/davudahmedoff/following{/other_user}",
    "gists_url": "https://api.github.com/users/davudahmedoff/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/davudahmedoff/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/davudahmedoff/subscriptions",
    "organizations_url": "https://api.github.com/users/davudahmedoff/orgs",
    "repos_url": "https://api.github.com/users/davudahmedoff/repos",
    "events_url": "https://api.github.com/users/davudahmedoff/events{/privacy}",
    "received_events_url": "https://api.github.com/users/davudahmedoff/received_events",
    "type": "User",
    "site_admin": false,
    "name": "davudahmedoff",
    "company": "Emgage",
    "blog": "",
    "location": "Baku,Azerbaijan",
    "email": null,
    "hireable": null,
    "bio": "Front-end deverloper",
    "twitter_username": "davud_ahmedoff",
    "public_repos": 1,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2022-12-23T15:32:39Z",
    "updated_at": "2023-01-30T10:34:18Z"
  }